echo Creando snapshot consistente en Hetzner (sin parar el servicio)...
ssh root@46.225.97.185 "cd /opt/tsumevault && rm -f tsumevault_snapshot.db && sqlite3 tsumeVault.db '.backup tsumevault_snapshot.db' && sqlite3 tsumevault_snapshot.db 'PRAGMA integrity_check;'"
echo ^^^ Debe haber impreso "ok". Si no, NO continues.
pause
echo Descargando...
scp root@46.225.97.185:/opt/tsumevault/tsumevault_snapshot.db "%~dp0tsumeVault.db"
echo Verificando la copia local...
sqlite3 "%~dp0tsumeVault.db" "PRAGMA integrity_check;"
echo ^^^ Debe imprimir "ok". Hecho.